services:
  zipkin:
    image: docker.io/openzipkin/zipkin:latest
    restart: unless-stopped
    networks:
      - hbnet
    ports:
      - '9411:9411'
    environment:
      STORAGE_TYPE: mem

networks:
  hbnet:
    external: true