services:
  otel:
    image: docker.io/otel/opentelemetry-collector-contrib:latest
    restart: unless-stopped
    volumes:
      - ./config:/etc/otelcol-contrib:z,ro
    networks:
      - hbnet
    ports:
      - '1777:1777' # pprof extension
      - '13133:13133' # health_check extension
      - '55679:55679' # zpages extension
      - '4317:4317' # OTLP gRPC receiver
      - '4318:4318' # OTLP http receiver
      - '9412:9411' # Zipkin http receiver

networks:
  hbnet:
    external: true
