services:
  redis:
    image: docker.io/library/redis:alpine
    restart: unless-stopped
    volumes:
      - ./config:/usr/local/etc/redis:z
    networks:
      - hbnet
    ports:
      - '6379:6379'
    command: ['redis-server', '/usr/local/etc/redis/redis.conf']

networks:
  hbnet:
    external: true
